// blogs
export const STORE_BLOGS = 'STORE_BLOGS'
export const STORE_BLOG_DETAIL = 'STORE_BLOG_DETAIL'

// flash
export const STORE_FLASH_MESSAGE = 'STORE_FLASH_MESSAGE'
export const CLEAR_FLASH_MESSAGE = 'CLEAR_FLASH_MESSAGE'
